[package]
name = "maturin-pyo3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "maturin_pyo3"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.0"
rand = "0.8.5"
